name: sym
description: "Patient-facing medication and symptom tracking app"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  
  # Models & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Local Storage (Hive - lightweight, performant for offline-first)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^17.1.2
  
  # Background & Sync
  workmanager: ^0.5.2
  connectivity_plus: ^6.0.3
  
  # Error Handling
  dartz: ^0.10.1
  
  # UI & Theming
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # Internationalization
  intl: ^0.19.0
  
  # Utilities
  uuid: ^4.4.0
  path_provider: ^2.1.3
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^5.0.0

  #icon generation
  flutter_launcher_icons: ^0.13.1
  
  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
